# Site settings
title: Artificial Intelligence and Statistics Conference
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aistats.org" # the base hostname & protocol for your site
twitter_username: aistat
github_username:  aistats

# Build settings
markdown: kramdown
