
# Site settings
title: Artificial Intelligence and Statistics Conference
email: aistats2018@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats

github:
  edit: true
  repository: aistats.github.io
TZ: UTC

# Build settings
markdown: kramdown

# change encoding for the generated output files to utf-8
encoding: utf-8

# Handling Reading
#safe:         false
#include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

image:
  file: fortlauderdale.jpg
  width: 400

banner:
  image: banner.png

credit_card_image: credit.png

conference:
  draft: true # set to True if the programme is draft only.
  logo: logo.jpg
  hide_tentative: true
  proceedings:
    url: http://proceedings.mlr.press/v54/
    show: true
  room: Room
  venue: Hyatt Pier 66 Hotel
  venue_url: https://pier66.hyatt.com/en/hotel/home.html
  location: Fort Lauderdale, Florida, USA
  full_name: Artificial Intelligence and Statistics
  name: AISTATS
  year: 2017
  instance: 20th
  styling: International Conference on
  dates:
  - 2017-04-20
  - 2017-04-22
  submission:
    url: https://cmt.research.microsoft.com/AISTATS2017/
    name: Microsoft CMT website
  deadlines:
  - name: Paper submission deadline
    type: submission
    time: 2016-10-13T23:59:00+0
  - name: Initial reviews available
    date: 2016-12-9
  - name: Author feedback deadline
    date: 2016-12-14
  - name: Paper decision notifications
    date: 2017-01-24
    type: decision
  - name: Camera ready (for accepted papers) deadline
    date: 2017-03-01
    type: camera-ready
  - name: Early registration deadline
    date: 2017-03-07
  - name: Regular registration deadline
    date: 2017-04-05
  chairs:
  - type: Program Chairs
    people:
    - family: Singh
      given: Aarti
      url: http://www.cs.cmu.edu/~aarti/
      institute: Machine Learning Department, Carnegie Mellon University
    - family: Zhu
      given: Jerry
      url: http://pages.cs.wisc.edu/~jerryzhu/
      institute: Department of Computer Sciences, University of Wisconsin -- Madison
  - type: Workflow Chairs
    people:
    - family: Alfeld
      given: Scott
      url: http://www.cs.wisc.edu/~salfeld
      institute: Department of Computer Sciences, University of Wisconsin -- Madison
    - family:  Yu
      given: Adams Wei
      url: http://www.cs.cmu.edu/~weiyu/
      institute: Machine Learning Department, Carnegie Mellon University
  - type: Publicity Chairs
    people:
    - family: Ramdas
      given: Aaditya
      url: http://www.cs.berkeley.edu/~aramdas
      institute: EECS and Statistics, University of California -- Berkeley
  - type: Publication Chair
    people:
    - family: Poczos
      given: Barnabas
      url: http://www.cs.cmu.edu/~bapoczos/
      institute: Machine Learning Department, Carnegie Mellon University
  - type: Fundraising Chair
    people:
    - family: Agarwal
      given: Alekh
      url: http://research.microsoft.com/en-us/um/people/alekha/
      institute: Microsoft Research, New York
  - type: Conference Admins
    people:
    - family: Smith
      given: Karen
    - family: Pregibon
      given: Daryl
  sponsors:
  - name: Disney Research
    logo: dr-logo-red.png
    url: http://www.disneyresearch.com
    width: 250
  - name: Google
    url: http://research.google.com
    logo: google.png
    width: 250
  - name: Netflix
    url: http://www.netflix.com
    logo: netflix.png
    width: 250
  - name: Tencent
    url: http://www.tencent.com
    logo: tencent.png
    width: 250
  - name: Springer
    logo: springer.png
    width: 300
    url: http://www.springer.com
  - name: Microsoft Research
    logo: MSFT_logo_rgb_C-Gray.png
    url: http://research.microsoft.com
    width: 300

previous_meeting:
  name:
  url: